services:
  postgres-db:
    image: postgres:17-alpine
    container_name: grit-postgres-db
    environment:
      - POSTGRES_DB=grit_db
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
      # Inyección del script de inicialización
      - ./docker/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    name: grit-postgres-net
    driver: bridge