-- V15__seed_entrenadores_atletas.sql
-- Seed data for GRIT: 50 active coaches, 50 pending coaches, 75 athletes.

BEGIN;

INSERT INTO usuarios (id, nombre, email, password_hash, rol, estado, created_at, updated_at)
VALUES (gen_random_uuid(), 'Iker Casillas', 'iker.casillas.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Sergio Ramos', 'sergio.ramos.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Gerard Piqué', 'gerard.pique.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Andrés Iniesta', 'andres.iniesta.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Xavi Hernández', 'xavi.hernandez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'David Villa', 'david.villa.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Fernando Torres', 'fernando.torres.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Sergio Busquets', 'sergio.busquets.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Juan Mata', 'juan.mata.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Jordi Alba', 'jordi.alba.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'César Azpilicueta', 'cesar.azpilicueta.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Kepa Arrizabalaga', 'kepa.arrizabalaga.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Marcos Alonso', 'marcos.alonso.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Dani Carvajal', 'dani.carvajal.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Héctor Bellerín', 'hector.bellerin.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Mikel Oyarzabal', 'mikel.oyarzabal.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Álvaro Morata', 'alvaro.morata.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Borja Iglesias', 'borja.iglesias.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Jesús Navas', 'jesus.navas.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Álvaro Negredo', 'alvaro.negredo.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Alexia Putellas', 'alexia.putellas.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Jenni Hermoso', 'jenni.hermoso.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Aitana Bonmatí', 'aitana.bonmati.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Olga Carmona', 'olga.carmona.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Mapi León', 'mapi.leon.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Irene Paredes', 'irene.paredes.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Marta Torrejón', 'marta.torrejon.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Mariona Caldentey', 'mariona.caldentey.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Sandra Paños', 'sandra.panos.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Vero Boquete', 'vero.boquete.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Patricia Guijarro', 'patricia.guijarro.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Amanda Sampedro', 'amanda.sampedro.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Ona Batlle', 'ona.batlle.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Leila Ouahabi', 'leila.ouahabi.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Lucía García', 'lucia.garcia.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Rafael Nadal', 'rafael.nadal.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Carlos Alcaraz', 'carlos.alcaraz.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Garbiñe Muguruza', 'garbine.muguruza.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Conchita Martínez', 'conchita.martinez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Arantxa Sánchez Vicario', 'arantxa.sanchezvicario.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'David Ferrer', 'david.ferrer.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Feliciano López', 'feliciano.lopez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Fernando Verdasco', 'fernando.verdasco.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Pablo Carreño Busta', 'pablo.carreno.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Paula Badosa', 'paula.badosa.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Sara Sorribes Tormo', 'sara.sorribes.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Anabel Medina Garrigues', 'anabel.medina.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Albert Ramos-Viñolas', 'albert.ramos.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Roberto Bautista Agut', 'roberto.bautista.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Nicolás Almagro', 'nicolas.almagro.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Guillermo García-López', 'guillermo.garcia.lopez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Carlos Moyá', 'carlos.moya.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Juan Carlos Ferrero', 'juan.carlos.ferrero.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Silvia Soler-Espinosa', 'silvia.soler.espinosa.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Albert Costa', 'albert.costa.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Pau Gasol', 'pau.gasol.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Marc Gasol', 'marc.gasol.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Ricky Rubio', 'ricky.rubio.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Juan Carlos Navarro', 'juan.carlos.navarro.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Sergio Llull', 'sergio.llull.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Rudy Fernández', 'rudy.fernandez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Jorge Garbajosa', 'jorge.garbajosa.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Alba Torrens', 'alba.torrens.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Laia Palau', 'laia.palau.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Cristina Ouviña', 'cristina.ouvina.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Álex Abrines', 'alex.abrines.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Fernando San Emeterio', 'fernando.sanemeterio.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Quino Colom', 'quino.colom.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Miguel Indurain', 'miguel.indurain.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Alberto Contador', 'alberto.contador.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Alejandro Valverde', 'alejandro.valverde.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Joaquim Rodríguez', 'joaquim.rodriguez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Óscar Pereiro', 'oscar.pereiro.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Óscar Freire', 'oscar.freire.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Luis León Sánchez', 'luis.leon.sanchez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Mikel Landa', 'mikel.landa.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Carlos Sastre', 'carlos.sastre.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Samuel Sánchez', 'samuel.sanchez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Enric Mas', 'enric.mas.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Pello Bilbao', 'pello.bilbao.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Jonathan Castroviejo', 'jonathan.castroviejo.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Ion Izagirre', 'ion.izagirre.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Gorka Izagirre', 'gorka.izagirre.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'José Joaquín Rojas', 'jose.joaquin.rojas.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'David de la Cruz', 'david.de.la.cruz.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Beñat Intxausti', 'benat.intxausti.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Mikel Nieve', 'mikel.nieve.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Ángel Vicioso', 'angel.vicioso.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Fernando Alonso', 'fernando.alonso.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Carlos Sainz', 'carlos.sainz.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Marc Márquez', 'marc.marquez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Jorge Lorenzo', 'jorge.lorenzo.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Dani Pedrosa', 'dani.pedrosa.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Joan Mir', 'joan.mir.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Pol Espargaró', 'pol.espargaro.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Maverick Viñales', 'maverick.vinales.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Alex Márquez', 'alex.marquez.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Ana Carrasco', 'ana.carrasco.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Laia Sanz', 'laia.sanz.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Pedro Acosta', 'pedro.acosta.entrenador@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ENTRENADOR', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Mireia Belmonte', 'mireia.belmonte.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'David Meca', 'david.meca.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Maialen Chourraut', 'maialen.chourraut.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Saúl Craviotto', 'saul.craviotto.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'David Cal', 'david.cal.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Blanca Manchón', 'blanca.manchon.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Teresa Portela', 'teresa.portela.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Ruth Beitia', 'ruth.beitia.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Orlando Ortega', 'orlando.ortega.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Fermín Cacho', 'fermin.cacho.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Ana Peleteiro', 'ana.peleteiro.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Marta Domínguez', 'marta.dominguez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Natalia Rodríguez', 'natalia.rodriguez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Bruno Hortelano', 'bruno.hortelano.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Asier Martínez', 'asier.martinez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Adel Mechaal', 'adel.mechaal.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Esther Guerrero', 'esther.guerrero.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Javier Gómez Noya', 'javier.gomez.noya.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Fernando Alarza', 'fernando.alarza.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Miriam Casillas', 'miriam.casillas.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Alberto Ginés López', 'alberto.gines.lopez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Jon Rahm', 'jon.rahm.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'José Manuel Abascal', 'jose.manuel.abascal.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Luis Alberto Hernando', 'luis.alberto.hernando.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Sandra Sánchez', 'sandra.sanchez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Iker Romero', 'iker.romero.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Marta Mangué', 'marta.mangue.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Teresa Zabell', 'teresa.zabell.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Iker Martínez', 'iker.martinez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'David Casinos', 'david.casinos.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Joel González', 'joel.gonzalez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Damián Quintero', 'damian.quintero.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Lydia Valentín', 'lydia.valentin.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Carlos Coloma', 'carlos.coloma.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Berta Betanzos', 'berta.betanzos.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Sergio García', 'sergio.garcia.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Carlota Ciganda', 'carlota.ciganda.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Azahara Muñoz', 'azahara.munoz.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Blanca Fernández Ochoa', 'blanca.fernandez.ochoa.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Francisco Fernández Ochoa', 'francisco.fernandez.ochoa.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Javier Fernández', 'javier.fernandez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'José María Olazábal', 'jose.maria.olazabal.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Luis Enrique', 'luis.enrique.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Vicente del Bosque', 'vicente.delbosque.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Pep Guardiola', 'pep.guardiola.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Julen Lopetegui', 'julen.lopetegui.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Diego Simeone', 'diego.simeone.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Pablo Laso', 'pablo.laso.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Xabi Alonso', 'xabi.alonso.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Marcos Llorente', 'marcos.llorente.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Juanfran Torres', 'juanfran.torres.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Patxi Usobiaga', 'patxi.usobiaga.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Martín Fiz', 'martin.fiz.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Rubén Ruzafa', 'ruben.ruzafa.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Francisco Ventoso', 'francisco.ventoso.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Ainhoa Murúa', 'ainhoa.murua.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Miki Oca', 'miki.oca.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'David Alegre', 'david.alegre.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Beatriz Ferrer-Salat', 'beatriz.ferrer.salat.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Kiko Martínez', 'kiko.martinez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Isabel Fernández', 'isabel.fernandez.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Tania Calvo', 'tania.calvo.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Sonia Franquet', 'sonia.franquet.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Miguel Luque', 'miguel.luque.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Sandra Aguilar', 'sandra.aguilar.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Borja Vivas', 'borja.vivas.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Oriol Romeu', 'oriol.romeu.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Víctor Valdés', 'victor.valdes.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Iago Aspas', 'iago.aspas.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Virginia Ruano Pascual', 'virginia.ruano.pascual.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Arantxa Parra Santonja', 'arantxa.parra.santonja.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Jorge Valdivia', 'jorge.valdivia.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Carolina Marín', 'carolina.marin.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Teresa Perales', 'teresa.perales.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (gen_random_uuid(), 'Julen Guerrero', 'julen.guerrero.atleta@grit.local',
        '$2b$12$I82xLlnG3ctFTnL1NtDljO5BeAqiJfCMgwyj/uT8XR2I9QT9BBezy', 'ATLETA', 'ACTIVO', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP)
;

INSERT INTO entrenadores (id, codigo_profesional, titulacion_entrenamiento, titulacion_nutricion, titulo_entrenamiento,
                          titulo_nutricion, experiencia_anos, descripcion, estado_revision, codigo_invitacion, foto_url)
VALUES ((SELECT id FROM usuarios WHERE email = 'iker.casillas.entrenador@grit.local'), 'PRO-0001', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 18, 'Entrenador de alto nivel con experiencia internacional.',
        'APROBADO', 'INV-0001', NULL),
       ((SELECT id FROM usuarios WHERE email = 'sergio.ramos.entrenador@grit.local'), 'PRO-0002', 'TSAF_TSEAS', 'TSD',
        true, true, 15, 'Especialista en preparación física y nutrición para atletas de élite.', 'APROBADO', 'INV-0002',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'gerard.pique.entrenador@grit.local'), 'PRO-0003', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 16,
        'Entrenador con experiencia en programas de fuerza y recuperación.', 'APROBADO', 'INV-0003', NULL),
       ((SELECT id FROM usuarios WHERE email = 'andres.iniesta.entrenador@grit.local'), 'PRO-0004', 'CERT_AFDA0210',
        'TSD', true, true, 14, 'Capacitado en entrenamiento funcional y control de macro nutrientes.', 'APROBADO',
        'INV-0004', NULL),
       ((SELECT id FROM usuarios WHERE email = 'xavi.hernandez.entrenador@grit.local'), 'PRO-0005', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 17,
        'Planificación de periodización y estrategias nutricionales de alto rendimiento.', 'APROBADO', 'INV-0005',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'david.villa.entrenador@grit.local'), 'PRO-0006', 'TSAF_TSEAS', 'TSD',
        true, true, 14, 'Entrenador orientado a resistencia y composición corporal.', 'APROBADO', 'INV-0006', NULL),
       ((SELECT id FROM usuarios WHERE email = 'fernando.torres.entrenador@grit.local'), 'PRO-0007', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 15, 'Experto en velocidad, agilidad y recuperación nutricional.',
        'APROBADO', 'INV-0007', NULL),
       ((SELECT id FROM usuarios WHERE email = 'sergio.busquets.entrenador@grit.local'), 'PRO-0008', 'CERT_AFDA0210',
        'TSD', true, true, 14, 'Entrenamiento táctico y planes alimentarios para equipo y atleta individual.',
        'APROBADO', 'INV-0008', NULL),
       ((SELECT id FROM usuarios WHERE email = 'juan.mata.entrenador@grit.local'), 'PRO-0009', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 13,
        'Especialista en fuerza de tren superior y nutrición de mantenimiento.', 'APROBADO', 'INV-0009', NULL),
       ((SELECT id FROM usuarios WHERE email = 'jordi.alba.entrenador@grit.local'), 'PRO-0010', 'TSAF_TSEAS', 'TSD',
        true, true, 12, 'Preparación física con foco en movilidad, prevención y alimentación saludable.', 'APROBADO',
        'INV-0010', NULL),
       ((SELECT id FROM usuarios WHERE email = 'cesar.azpilicueta.entrenador@grit.local'), 'PRO-0011', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 14, 'Metodologías de entrenamiento integral y nutrición deportiva.',
        'APROBADO', 'INV-0011', NULL),
       ((SELECT id FROM usuarios WHERE email = 'kepa.arrizabalaga.entrenador@grit.local'), 'PRO-0012', 'CERT_AFDA0210',
        'TSD', true, true, 11, 'Entrenador especializado en rendimiento bajo presión y control de peso.', 'APROBADO',
        'INV-0012', NULL),
       ((SELECT id FROM usuarios WHERE email = 'marcos.alonso.entrenador@grit.local'), 'PRO-0013', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 13, 'Atención personalizada para deportistas de campo y endurance.',
        'APROBADO', 'INV-0013', NULL),
       ((SELECT id FROM usuarios WHERE email = 'dani.carvajal.entrenador@grit.local'), 'PRO-0014', 'TSAF_TSEAS', 'TSD',
        true, true, 12, 'Coach con experiencia en fuerza explosiva y protocolos de recuperación.', 'APROBADO',
        'INV-0014', NULL),
       ((SELECT id FROM usuarios WHERE email = 'hector.bellerin.entrenador@grit.local'), 'PRO-0015', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 13,
        'Programas de mejora de resistencia y hábitos alimenticios sostenibles.', 'APROBADO', 'INV-0015', NULL),
       ((SELECT id FROM usuarios WHERE email = 'mikel.oyarzabal.entrenador@grit.local'), 'PRO-0016', 'CERT_AFDA0210',
        'TSD', true, true, 11, 'Entrenamiento moderno con especial foco en prevención de lesiones.', 'APROBADO',
        'INV-0016', NULL),
       ((SELECT id FROM usuarios WHERE email = 'alvaro.morata.entrenador@grit.local'), 'PRO-0017', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 12, 'Mejora de potencia y control de masa magra.', 'APROBADO',
        'INV-0017', NULL),
       ((SELECT id FROM usuarios WHERE email = 'borja.iglesias.entrenador@grit.local'), 'PRO-0018', 'TSAF_TSEAS', 'TSD',
        true, true, 12, 'Especialista en desarrollo de fuerza para atletas de contacto.', 'APROBADO', 'INV-0018', NULL),
       ((SELECT id FROM usuarios WHERE email = 'jesus.navas.entrenador@grit.local'), 'PRO-0019', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 13, 'Planes de entrenamiento para velocidad y recuperación activa.',
        'APROBADO', 'INV-0019', NULL),
       ((SELECT id FROM usuarios WHERE email = 'alvaro.negredo.entrenador@grit.local'), 'PRO-0020', 'CERT_AFDA0210',
        'TSD', true, true, 12, 'Enfoque en hipertrofia muscular y estrategia de nutrición diaria.', 'APROBADO',
        'INV-0020', NULL),
       ((SELECT id FROM usuarios WHERE email = 'alexia.putellas.entrenador@grit.local'), 'PRO-0021', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 14,
        'Entrenadora especializada en rendimiento femenino y periodización.', 'APROBADO', 'INV-0021', NULL),
       ((SELECT id FROM usuarios WHERE email = 'jenni.hermoso.entrenador@grit.local'), 'PRO-0022', 'TSAF_TSEAS', 'TSD',
        true, true, 13, 'Coach de fuerza, nutrición y preparación mental para deportistas de equipo.', 'APROBADO',
        'INV-0022', NULL),
       ((SELECT id FROM usuarios WHERE email = 'aitana.bonmati.entrenador@grit.local'), 'PRO-0023', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 12, 'Programas de alta exigencia para atletas femeninas y mixtas.',
        'APROBADO', 'INV-0023', NULL),
       ((SELECT id FROM usuarios WHERE email = 'olga.carmona.entrenador@grit.local'), 'PRO-0024', 'CERT_AFDA0210',
        'TSD', true, true, 11, 'Foco en estabilidad, velocidad y nutrición de mantenimiento.', 'APROBADO', 'INV-0024',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'mapi.leon.entrenador@grit.local'), 'PRO-0025', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 12,
        'Entrenador con experiencia en prevención de lesiones y biometría.', 'APROBADO', 'INV-0025', NULL),
       ((SELECT id FROM usuarios WHERE email = 'irene.paredes.entrenador@grit.local'), 'PRO-0026', 'TSAF_TSEAS', 'TSD',
        true, true, 13, 'Planes enfocados en fuerza funcional y suplementación limpia.', 'APROBADO', 'INV-0026', NULL),
       ((SELECT id FROM usuarios WHERE email = 'marta.torrejon.entrenador@grit.local'), 'PRO-0027', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 12, 'Coach especializado en resistencia y composición corporal.',
        'APROBADO', 'INV-0027', NULL),
       ((SELECT id FROM usuarios WHERE email = 'mariona.caldentey.entrenador@grit.local'), 'PRO-0028', 'CERT_AFDA0210',
        'TSD', true, true, 11, 'Formación en fuerza y nutrición para atletas olímpicos.', 'APROBADO', 'INV-0028', NULL),
       ((SELECT id FROM usuarios WHERE email = 'sandra.panos.entrenador@grit.local'), 'PRO-0029', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 13, 'Planificación de recuperación y hábitos alimenticios saludables.',
        'APROBADO', 'INV-0029', NULL),
       ((SELECT id FROM usuarios WHERE email = 'vero.boquete.entrenador@grit.local'), 'PRO-0030', 'TSAF_TSEAS', 'TSD',
        true, true, 12, 'Programas de endurance con soporte nutricional personalizado.', 'APROBADO', 'INV-0030', NULL),
       ((SELECT id FROM usuarios WHERE email = 'patricia.guijarro.entrenador@grit.local'), 'PRO-0031', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 12,
        'Entrenador con enfoque en fuerza útil y alimentación equilibrada.', 'APROBADO', 'INV-0031', NULL),
       ((SELECT id FROM usuarios WHERE email = 'amanda.sampedro.entrenador@grit.local'), 'PRO-0032', 'CERT_AFDA0210',
        'TSD', true, true, 11, 'Especialida en resistencia y planes de macronutrientes.', 'APROBADO', 'INV-0032', NULL),
       ((SELECT id FROM usuarios WHERE email = 'ona.batlle.entrenador@grit.local'), 'PRO-0033', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 12, 'Entrenador con experiencia en movilidad y fuerza dinámica.',
        'APROBADO', 'INV-0033', NULL),
       ((SELECT id FROM usuarios WHERE email = 'leila.ouahabi.entrenador@grit.local'), 'PRO-0034', 'TSAF_TSEAS', 'TSD',
        true, true, 11, 'Programas de fuerza y nutrición para deportistas de élite.', 'APROBADO', 'INV-0034', NULL),
       ((SELECT id FROM usuarios WHERE email = 'lucia.garcia.entrenador@grit.local'), 'PRO-0035', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 12, 'Experta en preparación física y régimen alimenticio.', 'APROBADO',
        'INV-0035', NULL),
       ((SELECT id FROM usuarios WHERE email = 'rafael.nadal.entrenador@grit.local'), 'PRO-0036', 'CERT_AFDA0210',
        'TSD', true, true, 15, 'Entrenador centrado en potencia, resistencia y recuperación muscular.', 'APROBADO',
        'INV-0036', NULL),
       ((SELECT id FROM usuarios WHERE email = 'carlos.alcaraz.entrenador@grit.local'), 'PRO-0037', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 10, 'Programa de alta intensidad y control de carga.', 'APROBADO',
        'INV-0037', NULL),
       ((SELECT id FROM usuarios WHERE email = 'garbine.muguruza.entrenador@grit.local'), 'PRO-0038', 'TSAF_TSEAS',
        'TSD', true, true, 11, 'Entrenamiento con foco en explosividad y energía.', 'APROBADO', 'INV-0038', NULL),
       ((SELECT id FROM usuarios WHERE email = 'conchita.martinez.entrenador@grit.local'), 'PRO-0039', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 16, 'Experiencia en preparación olímpica y control de macros.',
        'APROBADO', 'INV-0039', NULL),
       ((SELECT id FROM usuarios WHERE email = 'arantxa.sanchezvicario.entrenador@grit.local'), 'PRO-0040',
        'CERT_AFDA0210', 'TSD', true, true, 16, 'Planes de recuperación y nutrición deportiva de alto nivel.',
        'APROBADO', 'INV-0040', NULL),
       ((SELECT id FROM usuarios WHERE email = 'david.ferrer.entrenador@grit.local'), 'PRO-0041', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 14, 'Trabajo de resistencia y control del peso de competición.',
        'APROBADO', 'INV-0041', NULL),
       ((SELECT id FROM usuarios WHERE email = 'feliciano.lopez.entrenador@grit.local'), 'PRO-0042', 'TSAF_TSEAS',
        'TSD', true, true, 13, 'Fuerza de base y suplementación saludable para deportistas.', 'APROBADO', 'INV-0042',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'fernando.verdasco.entrenador@grit.local'), 'PRO-0043', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 14, 'Entrenamiento físico con visión integral del rendimiento.',
        'APROBADO', 'INV-0043', NULL),
       ((SELECT id FROM usuarios WHERE email = 'pablo.carreno.entrenador@grit.local'), 'PRO-0044', 'CERT_AFDA0210',
        'TSD', true, true, 12, 'Preparación de fuerza y nutrición equilibrada para tenis.', 'APROBADO', 'INV-0044',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'paula.badosa.entrenador@grit.local'), 'PRO-0045', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 11, 'Programas de recuperación y alimentación en competición.',
        'APROBADO', 'INV-0045', NULL),
       ((SELECT id FROM usuarios WHERE email = 'sara.sorribes.entrenador@grit.local'), 'PRO-0046', 'TSAF_TSEAS', 'TSD',
        true, true, 11, 'Coach orientada a entrenamiento específico y dieta deportiva.', 'APROBADO', 'INV-0046', NULL),
       ((SELECT id FROM usuarios WHERE email = 'anabel.medina.entrenador@grit.local'), 'PRO-0047', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 12, 'Especializada en fisiología del ejercicio y nutrición deportiva.',
        'APROBADO', 'INV-0047', NULL),
       ((SELECT id FROM usuarios WHERE email = 'albert.ramos.entrenador@grit.local'), 'PRO-0048', 'CERT_AFDA0210',
        'TSD', true, true, 11, 'Entrenador con foco en triatlón y soporte alimentario.', 'APROBADO', 'INV-0048', NULL),
       ((SELECT id FROM usuarios WHERE email = 'roberto.bautista.entrenador@grit.local'), 'PRO-0049', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 12, 'Formación en resistencia y nutrición de rendimiento.', 'APROBADO',
        'INV-0049', NULL),
       ((SELECT id FROM usuarios WHERE email = 'nicolas.almagro.entrenador@grit.local'), 'PRO-0050', 'TSAF_TSEAS',
        'TSD', true, true, 12, 'Coach con experiencia en entrenamiento físico y dieta competitiva.', 'APROBADO',
        'INV-0050', NULL),
       ((SELECT id FROM usuarios WHERE email = 'guillermo.garcia.lopez.entrenador@grit.local'), 'PRO-0051',
        'GRADO_CAFYD', 'GRADO_NUTRICION_DIETETICA', true, true, 12, 'Nutrición y técnica para atletas de resistencia.',
        'PENDIENTE_REVISION', 'INV-0051', NULL),
       ((SELECT id FROM usuarios WHERE email = 'carlos.moya.entrenador@grit.local'), 'PRO-0052', 'TSAF_TSEAS', 'TSD',
        true, true, 13, 'Entrenamiento aeróbico y alimentación saludable para corredores.', 'PENDIENTE_REVISION',
        'INV-0052', NULL),
       ((SELECT id FROM usuarios WHERE email = 'juan.carlos.ferrero.entrenador@grit.local'), 'PRO-0053', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 15, 'Planes de recuperación y nutrición en tenis profesional.',
        'PENDIENTE_REVISION', 'INV-0053', NULL),
       ((SELECT id FROM usuarios WHERE email = 'silvia.soler.espinosa.entrenador@grit.local'), 'PRO-0054',
        'CERT_AFDA0210', 'TSD', true, true, 12, 'Programa de fuerza y nutrición para deportistas femeninas.',
        'PENDIENTE_REVISION', 'INV-0054', NULL),
       ((SELECT id FROM usuarios WHERE email = 'albert.costa.entrenador@grit.local'), 'PRO-0055', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 14, 'Entrenamiento de alta intensidad y macronutrientes balanceados.',
        'PENDIENTE_REVISION', 'INV-0055', NULL),
       ((SELECT id FROM usuarios WHERE email = 'pau.gasol.entrenador@grit.local'), 'PRO-0056', 'TSAF_TSEAS', 'TSD',
        true, true, 18, 'Preparación física especializada en baloncesto y nutrición de equipo.', 'PENDIENTE_REVISION',
        'INV-0056', NULL),
       ((SELECT id FROM usuarios WHERE email = 'marc.gasol.entrenador@grit.local'), 'PRO-0057', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 18, 'Coach con experiencia en fuerza y planificación estratégica.',
        'PENDIENTE_REVISION', 'INV-0057', NULL),
       ((SELECT id FROM usuarios WHERE email = 'ricky.rubio.entrenador@grit.local'), 'PRO-0058', 'CERT_AFDA0210', 'TSD',
        true, true, 17, 'Programas de movilidad, salto y dieta equilibrada.', 'PENDIENTE_REVISION', 'INV-0058', NULL),
       ((SELECT id FROM usuarios WHERE email = 'juan.carlos.navarro.entrenador@grit.local'), 'PRO-0059', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 16,
        'Entrenamiento de resistencia y planes alimentarios de alto rendimiento.', 'PENDIENTE_REVISION', 'INV-0059',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'sergio.llull.entrenador@grit.local'), 'PRO-0060', 'TSAF_TSEAS', 'TSD',
        true, true, 15, 'Coach de juego rápido, agilidad y nutrición deportiva.', 'PENDIENTE_REVISION', 'INV-0060',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'rudy.fernandez.entrenador@grit.local'), 'PRO-0061', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 16, 'Fuerza funcional y planes de dieta para rendimiento prolongado.',
        'PENDIENTE_REVISION', 'INV-0061', NULL),
       ((SELECT id FROM usuarios WHERE email = 'jorge.garbajosa.entrenador@grit.local'), 'PRO-0062', 'CERT_AFDA0210',
        'TSD', true, true, 16, 'Entrenamiento de explosividad y control de peso corporal.', 'PENDIENTE_REVISION',
        'INV-0062', NULL),
       ((SELECT id FROM usuarios WHERE email = 'alba.torrens.entrenador@grit.local'), 'PRO-0063', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 16,
        'Planificación para deportistas de alto rendimiento internacional.', 'PENDIENTE_REVISION', 'INV-0063', NULL),
       ((SELECT id FROM usuarios WHERE email = 'laia.palau.entrenador@grit.local'), 'PRO-0064', 'TSAF_TSEAS', 'TSD',
        true, true, 17, 'Entrenamiento de equipo y nutrición en deportes de alta exigencia.', 'PENDIENTE_REVISION',
        'INV-0064', NULL),
       ((SELECT id FROM usuarios WHERE email = 'cristina.ouvina.entrenador@grit.local'), 'PRO-0065', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 15, 'Fuerza y resistencia combinada con nutrición consciente.',
        'PENDIENTE_REVISION', 'INV-0065', NULL),
       ((SELECT id FROM usuarios WHERE email = 'alex.abrines.entrenador@grit.local'), 'PRO-0066', 'CERT_AFDA0210',
        'TSD', true, true, 14, 'Preparación deportiva y nutrición para atletismo de alto nivel.', 'PENDIENTE_REVISION',
        'INV-0066', NULL),
       ((SELECT id FROM usuarios WHERE email = 'fernando.sanemeterio.entrenador@grit.local'), 'PRO-0067', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 16, 'Entrenamiento de fuerza y estrategias de recuperación.',
        'PENDIENTE_REVISION', 'INV-0067', NULL),
       ((SELECT id FROM usuarios WHERE email = 'quino.colom.entrenador@grit.local'), 'PRO-0068', 'TSAF_TSEAS', 'TSD',
        true, true, 14, 'Coach de agility, potencia y balance nutricional.', 'PENDIENTE_REVISION', 'INV-0068', NULL),
       ((SELECT id FROM usuarios WHERE email = 'miguel.indurain.entrenador@grit.local'), 'PRO-0069', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 19, 'Especialista en endurance, ciclismo y nutrición de resistencia.',
        'PENDIENTE_REVISION', 'INV-0069', NULL),
       ((SELECT id FROM usuarios WHERE email = 'alberto.contador.entrenador@grit.local'), 'PRO-0070', 'CERT_AFDA0210',
        'TSD', true, true, 18, 'Entrenamiento para ciclismo de subida y planes de carbohidratos.', 'PENDIENTE_REVISION',
        'INV-0070', NULL),
       ((SELECT id FROM usuarios WHERE email = 'alejandro.valverde.entrenador@grit.local'), 'PRO-0071', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 18, 'Plan de rendimiento y recuperación para etapas de carrera.',
        'PENDIENTE_REVISION', 'INV-0071', NULL),
       ((SELECT id FROM usuarios WHERE email = 'joaquim.rodriguez.entrenador@grit.local'), 'PRO-0072', 'TSAF_TSEAS',
        'TSD', true, true, 17, 'Coaching de explosividad y nutrición competitiva.', 'PENDIENTE_REVISION', 'INV-0072',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'oscar.pereiro.entrenador@grit.local'), 'PRO-0073', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 16, 'Preparación de resistencia y manejo de energía.',
        'PENDIENTE_REVISION', 'INV-0073', NULL),
       ((SELECT id FROM usuarios WHERE email = 'oscar.freire.entrenador@grit.local'), 'PRO-0074', 'CERT_AFDA0210',
        'TSD', true, true, 16, 'Coach de sprints y nutrición para finalizaciones explosivas.', 'PENDIENTE_REVISION',
        'INV-0074', NULL),
       ((SELECT id FROM usuarios WHERE email = 'luis.leon.sanchez.entrenador@grit.local'), 'PRO-0075', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 17, 'Especialista en ciclismo y optimización de la dieta.',
        'PENDIENTE_REVISION', 'INV-0075', NULL),
       ((SELECT id FROM usuarios WHERE email = 'mikel.landa.entrenador@grit.local'), 'PRO-0076', 'TSAF_TSEAS', 'TSD',
        true, true, 16, 'Entrenador para contrarreloj y recuperación activa.', 'PENDIENTE_REVISION', 'INV-0076', NULL),
       ((SELECT id FROM usuarios WHERE email = 'carlos.sastre.entrenador@grit.local'), 'PRO-0077', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 18, 'Programas de resistencia con enfoque en composición corporal.',
        'PENDIENTE_REVISION', 'INV-0077', NULL),
       ((SELECT id FROM usuarios WHERE email = 'samuel.sanchez.entrenador@grit.local'), 'PRO-0078', 'CERT_AFDA0210',
        'TSD', true, true, 16, 'Técnicas de recuperación y alimentación para ciclistas.', 'PENDIENTE_REVISION',
        'INV-0078', NULL),
       ((SELECT id FROM usuarios WHERE email = 'enric.mas.entrenador@grit.local'), 'PRO-0079', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 16, 'Coaching en montaña y control de la hidratación.',
        'PENDIENTE_REVISION', 'INV-0079', NULL),
       ((SELECT id FROM usuarios WHERE email = 'pello.bilbao.entrenador@grit.local'), 'PRO-0080', 'TSAF_TSEAS', 'TSD',
        true, true, 15, 'Entrenamiento de resistencia y planes de recuperación.', 'PENDIENTE_REVISION', 'INV-0080',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'jonathan.castroviejo.entrenador@grit.local'), 'PRO-0081', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 15, 'Coach de resistencia y alimentación saludable.',
        'PENDIENTE_REVISION', 'INV-0081', NULL),
       ((SELECT id FROM usuarios WHERE email = 'ion.izagirre.entrenador@grit.local'), 'PRO-0082', 'CERT_AFDA0210',
        'TSD', true, true, 14, 'Programas de potencia y nutrición para escalada y ciclismo.', 'PENDIENTE_REVISION',
        'INV-0082', NULL),
       ((SELECT id FROM usuarios WHERE email = 'gorka.izagirre.entrenador@grit.local'), 'PRO-0083', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 14, 'Entrenador con experiencia en crono y adaptaciones alimentarias.',
        'PENDIENTE_REVISION', 'INV-0083', NULL),
       ((SELECT id FROM usuarios WHERE email = 'jose.joaquin.rojas.entrenador@grit.local'), 'PRO-0084', 'TSAF_TSEAS',
        'TSD', true, true, 15, 'Coach de resistencia y planes de hidratación.', 'PENDIENTE_REVISION', 'INV-0084', NULL),
       ((SELECT id FROM usuarios WHERE email = 'david.de.la.cruz.entrenador@grit.local'), 'PRO-0085', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 15, 'Preparación de resistencia con control de energía.',
        'PENDIENTE_REVISION', 'INV-0085', NULL),
       ((SELECT id FROM usuarios WHERE email = 'benat.intxausti.entrenador@grit.local'), 'PRO-0086', 'CERT_AFDA0210',
        'TSD', true, true, 14, 'Entrenamiento de fondo y alimentación de competencia.', 'PENDIENTE_REVISION',
        'INV-0086', NULL),
       ((SELECT id FROM usuarios WHERE email = 'mikel.nieve.entrenador@grit.local'), 'PRO-0087', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 14, 'Resistencia en altura y nutrición de recuperación.',
        'PENDIENTE_REVISION', 'INV-0087', NULL),
       ((SELECT id FROM usuarios WHERE email = 'angel.vicioso.entrenador@grit.local'), 'PRO-0088', 'TSAF_TSEAS', 'TSD',
        true, true, 15, 'Programas de fuerza y velocidad para ciclismo.', 'PENDIENTE_REVISION', 'INV-0088', NULL),
       ((SELECT id FROM usuarios WHERE email = 'fernando.alonso.entrenador@grit.local'), 'PRO-0089', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 18, 'Coach con enfoque en precisión, resistencia y alimentación.',
        'PENDIENTE_REVISION', 'INV-0089', NULL),
       ((SELECT id FROM usuarios WHERE email = 'carlos.sainz.entrenador@grit.local'), 'PRO-0090', 'CERT_AFDA0210',
        'TSD', true, true, 17, 'Preparación física y recuperación para motorsport.', 'PENDIENTE_REVISION', 'INV-0090',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'marc.marquez.entrenador@grit.local'), 'PRO-0091', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 16, 'Entrenamiento de reflejos, equilibrio y dieta competitiva.',
        'PENDIENTE_REVISION', 'INV-0091', NULL),
       ((SELECT id FROM usuarios WHERE email = 'jorge.lorenzo.entrenador@grit.local'), 'PRO-0092', 'TSAF_TSEAS', 'TSD',
        true, true, 16, 'Programas de fuerza y recuperación para motos de alta velocidad.', 'PENDIENTE_REVISION',
        'INV-0092', NULL),
       ((SELECT id FROM usuarios WHERE email = 'dani.pedrosa.entrenador@grit.local'), 'PRO-0093', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 15, 'Entrenamiento funcional y dieta para pilotos de competición.',
        'PENDIENTE_REVISION', 'INV-0093', NULL),
       ((SELECT id FROM usuarios WHERE email = 'joan.mir.entrenador@grit.local'), 'PRO-0094', 'CERT_AFDA0210', 'TSD',
        true, true, 15, 'Coach de equilibrio, fuerza y nutrición para motoristas.', 'PENDIENTE_REVISION', 'INV-0094',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'pol.espargaro.entrenador@grit.local'), 'PRO-0095', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 15, 'Preparación de potencia y gestión de peso corporal.',
        'PENDIENTE_REVISION', 'INV-0095', NULL),
       ((SELECT id FROM usuarios WHERE email = 'maverick.vinales.entrenador@grit.local'), 'PRO-0096', 'TSAF_TSEAS',
        'TSD', true, true, 15, 'Entrenamiento de reflejos y nutrición para motos.', 'PENDIENTE_REVISION', 'INV-0096',
        NULL),
       ((SELECT id FROM usuarios WHERE email = 'alex.marquez.entrenador@grit.local'), 'PRO-0097', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 14, 'Coach enfocado en velocidad y recuperación.',
        'PENDIENTE_REVISION', 'INV-0097', NULL),
       ((SELECT id FROM usuarios WHERE email = 'ana.carrasco.entrenador@grit.local'), 'PRO-0098', 'CERT_AFDA0210',
        'TSD', true, true, 14, 'Entrenamiento de motoristas y alimentación de alto rendimiento.', 'PENDIENTE_REVISION',
        'INV-0098', NULL),
       ((SELECT id FROM usuarios WHERE email = 'laia.sanz.entrenador@grit.local'), 'PRO-0099', 'GRADO_CAFYD',
        'GRADO_NUTRICION_DIETETICA', true, true, 18, 'Coach de resistencia, motocross y nutrición de potencia.',
        'PENDIENTE_REVISION', 'INV-0099', NULL),
       ((SELECT id FROM usuarios WHERE email = 'pedro.acosta.entrenador@grit.local'), 'PRO-0100', 'TSAF_TSEAS', 'TSD',
        true, true, 13, 'Entrenamiento y nutrición para pilotos jóvenes de alto nivel.', 'PENDIENTE_REVISION',
        'INV-0100', NULL)
;

INSERT INTO atletas (id, fecha_nac, genero, peso_kg, altura_cm, deporte, nivel, servicio, objetivo)
VALUES ((SELECT id FROM usuarios WHERE email = 'mireia.belmonte.atleta@grit.local'), '1990-11-10', 'MUJER', 68.50, 175,
        'Natación', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'david.meca.atleta@grit.local'), '1974-01-07', 'HOMBRE', 80.00, 184,
        'Natación', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'maialen.chourraut.atleta@grit.local'), '1983-04-08', 'MUJER', 64.00,
        169, 'Piragüismo', 'ELITE', 'ENTRENAMIENTO', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'saul.craviotto.atleta@grit.local'), '1984-11-03', 'HOMBRE', 72.00, 177,
        'Piragüismo', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'david.cal.atleta@grit.local'), '1982-12-10', 'HOMBRE', 74.00, 176,
        'Piragüismo', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'blanca.manchon.atleta@grit.local'), '1987-04-17', 'MUJER', 61.00, 167,
        'Vela', 'AVANZADO', 'ENTRENAMIENTO', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'teresa.portela.atleta@grit.local'), '1982-05-10', 'MUJER', 63.50, 168,
        'Piragüismo', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'ruth.beitia.atleta@grit.local'), '1981-04-20', 'MUJER', 56.00, 180,
        'Atletismo', 'ELITE', 'ENTRENAMIENTO', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'orlando.ortega.atleta@grit.local'), '1991-07-27', 'HOMBRE', 72.00, 180,
        'Atletismo', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'fermin.cacho.atleta@grit.local'), '1969-02-16', 'HOMBRE', 68.00, 178,
        'Atletismo', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'ana.peleteiro.atleta@grit.local'), '1995-10-23', 'MUJER', 67.00, 172,
        'Atletismo', 'ELITE', 'ENTRENAMIENTO', 'MASA_MUSCULAR'),
       ((SELECT id FROM usuarios WHERE email = 'marta.dominguez.atleta@grit.local'), '1975-05-02', 'MUJER', 64.00, 170,
        'Atletismo', 'AVANZADO', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'natalia.rodriguez.atleta@grit.local'), '1982-02-18', 'MUJER', 61.00,
        168, 'Atletismo', 'AVANZADO', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'bruno.hortelano.atleta@grit.local'), '1991-07-18', 'HOMBRE', 72.00, 178,
        'Atletismo', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'asier.martinez.atleta@grit.local'), '2000-09-08', 'HOMBRE', 70.00, 176,
        'Atletismo', 'AVANZADO', 'ENTRENAMIENTO', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'adel.mechaal.atleta@grit.local'), '1990-05-26', 'HOMBRE', 69.50, 177,
        'Atletismo', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'esther.guerrero.atleta@grit.local'), '1994-10-11', 'MUJER', 58.00, 165,
        'Atletismo', 'AVANZADO', 'ENTRENAMIENTO', 'PERDER_PESO'),
       ((SELECT id FROM usuarios WHERE email = 'javier.gomez.noya.atleta@grit.local'), '1983-03-25', 'HOMBRE', 68.00,
        176, 'Triatlón', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'fernando.alarza.atleta@grit.local'), '1991-01-22', 'HOMBRE', 70.00, 178,
        'Triatlón', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'miriam.casillas.atleta@grit.local'), '1992-07-13', 'MUJER', 62.00, 168,
        'Triatlón', 'AVANZADO', 'ENTRENAMIENTO', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'alberto.gines.lopez.atleta@grit.local'), '2002-08-24', 'HOMBRE', 68.00,
        174, 'Escalada', 'AVANZADO', 'ENTRENAMIENTO', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'jon.rahm.atleta@grit.local'), '1994-11-10', 'HOMBRE', 82.00, 188,
        'Golf', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'jose.manuel.abascal.atleta@grit.local'), '1958-11-17', 'HOMBRE', 70.00,
        178, 'Atletismo', 'ELITE', 'ENTRENAMIENTO', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'luis.alberto.hernando.atleta@grit.local'), '1977-07-18', 'HOMBRE',
        72.00, 176, 'Trailrunning', 'ELITE', 'ENTRENAMIENTO', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'sandra.sanchez.atleta@grit.local'), '1991-09-16', 'MUJER', 54.00, 166,
        'Kárate', 'ELITE', 'ENTRENAMIENTO', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'iker.romero.atleta@grit.local'), '1980-08-15', 'HOMBRE', 92.00, 196,
        'Balonmano', 'ELITE', 'NUTRICION', 'MASA_MUSCULAR'),
       ((SELECT id FROM usuarios WHERE email = 'marta.mangue.atleta@grit.local'), '1983-04-23', 'MUJER', 65.00, 171,
        'Balonmano', 'ELITE', 'NUTRICION', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'teresa.zabell.atleta@grit.local'), '1972-10-20', 'MUJER', 62.00, 169,
        'Vela', 'AVANZADO', 'NUTRICION', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'iker.martinez.atleta@grit.local'), '1977-11-23', 'HOMBRE', 71.00, 174,
        'Vela', 'AVANZADO', 'NUTRICION', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'david.casinos.atleta@grit.local'), '1972-11-03', 'HOMBRE', 79.00, 180,
        'Atletismo Paralímpico', 'AVANZADO', 'NUTRICION', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'joel.gonzalez.atleta@grit.local'), '1990-01-21', 'HOMBRE', 68.00, 175,
        'Taekwondo', 'ELITE', 'NUTRICION', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'damian.quintero.atleta@grit.local'), '1984-10-05', 'HOMBRE', 68.00, 175,
        'Kárate', 'ELITE', 'NUTRICION', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'lydia.valentin.atleta@grit.local'), '1985-02-10', 'MUJER', 72.00, 168,
        'Halterofilia', 'ELITE', 'NUTRICION', 'MASA_MUSCULAR'),
       ((SELECT id FROM usuarios WHERE email = 'carlos.coloma.atleta@grit.local'), '1981-04-23', 'HOMBRE', 68.00, 178,
        'Ciclismo', 'ELITE', 'NUTRICION', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'berta.betanzos.atleta@grit.local'), '1988-10-27', 'MUJER', 56.00, 166,
        'Vela', 'AVANZADO', 'NUTRICION', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'sergio.garcia.atleta@grit.local'), '1980-01-09', 'HOMBRE', 82.00, 176,
        'Golf', 'ELITE', 'NUTRICION', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'carlota.ciganda.atleta@grit.local'), '1990-01-02', 'MUJER', 68.00, 176,
        'Golf', 'AVANZADO', 'NUTRICION', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'azahara.munoz.atleta@grit.local'), '1987-08-29', 'MUJER', 62.00, 169,
        'Golf', 'AVANZADO', 'NUTRICION', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'blanca.fernandez.ochoa.atleta@grit.local'), '1963-04-22', 'MUJER',
        60.00, 165, 'Esquí', 'ELITE', 'NUTRICION', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'francisco.fernandez.ochoa.atleta@grit.local'), '1950-04-25', 'HOMBRE',
        76.00, 177, 'Esquí', 'ELITE', 'NUTRICION', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'javier.fernandez.atleta@grit.local'), '1991-04-15', 'HOMBRE', 72.00,
        174, 'Patinaje', 'ELITE', 'NUTRICION', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'jose.maria.olazabal.atleta@grit.local'), '1966-02-05', 'HOMBRE', 78.00,
        176, 'Golf', 'ELITE', 'NUTRICION', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'luis.enrique.atleta@grit.local'), '1970-05-08', 'HOMBRE', 75.00, 180,
        'Fútbol', 'ELITE', 'NUTRICION', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'vicente.delbosque.atleta@grit.local'), '1950-12-23', 'HOMBRE', 78.00,
        176, 'Fútbol', 'ELITE', 'NUTRICION', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'pep.guardiola.atleta@grit.local'), '1971-01-18', 'HOMBRE', 70.00, 180,
        'Fútbol', 'ELITE', 'NUTRICION', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'julen.lopetegui.atleta@grit.local'), '1966-08-28', 'HOMBRE', 74.00, 181,
        'Fútbol', 'ELITE', 'NUTRICION', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'diego.simeone.atleta@grit.local'), '1970-04-28', 'HOMBRE', 74.00, 176,
        'Fútbol', 'ELITE', 'NUTRICION', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'pablo.laso.atleta@grit.local'), '1967-03-21', 'HOMBRE', 80.00, 190,
        'Baloncesto', 'ELITE', 'NUTRICION', 'MASA_MUSCULAR'),
       ((SELECT id FROM usuarios WHERE email = 'xabi.alonso.atleta@grit.local'), '1981-11-25', 'HOMBRE', 75.00, 183,
        'Fútbol', 'ELITE', 'NUTRICION', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'marcos.llorente.atleta@grit.local'), '1995-01-30', 'HOMBRE', 77.00, 182,
        'Fútbol', 'ELITE', 'NUTRICION', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'juanfran.torres.atleta@grit.local'), '1986-01-07', 'HOMBRE', 76.00, 181,
        'Fútbol', 'ELITE', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'patxi.usobiaga.atleta@grit.local'), '1980-10-24', 'HOMBRE', 70.00, 176,
        'Escalada', 'ELITE', 'AMBOS', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'martin.fiz.atleta@grit.local'), '1963-03-03', 'HOMBRE', 68.00, 176,
        'Atletismo', 'ELITE', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'ruben.ruzafa.atleta@grit.local'), '1987-08-09', 'HOMBRE', 70.00, 175,
        'Triatlón', 'ELITE', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'francisco.ventoso.atleta@grit.local'), '1982-03-11', 'HOMBRE', 73.00,
        181, 'Ciclismo', 'ELITE', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'ainhoa.murua.atleta@grit.local'), '1980-07-27', 'MUJER', 57.00, 166,
        'Triatlón', 'AVANZADO', 'AMBOS', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'miki.oca.atleta@grit.local'), '1979-09-28', 'HOMBRE', 87.00, 188,
        'Waterpolo', 'ELITE', 'AMBOS', 'MASA_MUSCULAR'),
       ((SELECT id FROM usuarios WHERE email = 'david.alegre.atleta@grit.local'), '1981-12-13', 'HOMBRE', 76.00, 183,
        'Hockey', 'AVANZADO', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'beatriz.ferrer.salat.atleta@grit.local'), '1966-09-13', 'MUJER', 58.00,
        168, 'Equitación', 'ELITE', 'AMBOS', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'kiko.martinez.atleta@grit.local'), '1982-09-20', 'HOMBRE', 69.00, 175,
        'Boxeo', 'ELITE', 'AMBOS', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'isabel.fernandez.atleta@grit.local'), '1972-09-22', 'MUJER', 65.00, 170,
        'Judo', 'ELITE', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'tania.calvo.atleta@grit.local'), '1990-03-26', 'MUJER', 62.00, 169,
        'Ciclismo', 'AVANZADO', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'sonia.franquet.atleta@grit.local'), '1980-01-10', 'MUJER', 58.00, 167,
        'Tiro', 'AVANZADO', 'AMBOS', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'miguel.luque.atleta@grit.local'), '1988-09-24', 'HOMBRE', 78.00, 181,
        'Natación Paralímpica', 'AVANZADO', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'sandra.aguilar.atleta@grit.local'), '1994-08-09', 'MUJER', 53.00, 160,
        'Gimnasia', 'AVANZADO', 'AMBOS', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'borja.vivas.atleta@grit.local'), '1984-12-06', 'HOMBRE', 120.00, 205,
        'Atletismo', 'ELITE', 'AMBOS', 'MASA_MUSCULAR'),
       ((SELECT id FROM usuarios WHERE email = 'oriol.romeu.atleta@grit.local'), '1991-09-24', 'HOMBRE', 72.00, 180,
        'Fútbol', 'ELITE', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'victor.valdes.atleta@grit.local'), '1982-01-14', 'HOMBRE', 82.00, 185,
        'Fútbol', 'ELITE', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'iago.aspas.atleta@grit.local'), '1987-08-01', 'HOMBRE', 74.00, 179,
        'Fútbol', 'ELITE', 'AMBOS', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'virginia.ruano.pascual.atleta@grit.local'), '1973-04-25', 'MUJER',
        58.00, 170, 'Tenis', 'ELITE', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'arantxa.parra.santonja.atleta@grit.local'), '1982-08-10', 'MUJER',
        59.00, 168, 'Tenis', 'AVANZADO', 'AMBOS', 'SALUD'),
       ((SELECT id FROM usuarios WHERE email = 'jorge.valdivia.atleta@grit.local'), '1983-02-19', 'HOMBRE', 74.00, 173,
        'Fútbol', 'AVANZADO', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'carolina.marin.atleta@grit.local'), '1993-06-15', 'MUJER', 62.00, 169,
        'Bádminton', 'ELITE', 'AMBOS', 'RENDIMIENTO'),
       ((SELECT id FROM usuarios WHERE email = 'teresa.perales.atleta@grit.local'), '1975-12-29', 'MUJER', 58.00, 167,
        'Natación', 'ELITE', 'AMBOS', 'RESISTENCIA'),
       ((SELECT id FROM usuarios WHERE email = 'julen.guerrero.atleta@grit.local'), '1974-01-07', 'HOMBRE', 75.00, 178,
        'Fútbol', 'AVANZADO', 'AMBOS', 'RESISTENCIA')
;

INSERT INTO documentos_entrenador (id,
                                   entrenador_id,
                                   nombre_archivo,
                                   url_s3,
                                   tipo_mime,
                                   tamanyo_bytes,
                                   status,
                                   uploaded_at,
                                   reviewed_at)
SELECT gen_random_uuid(),
       id,
       'Acreditación oficial.pdf',
       's3://grit-docs/entrenador-' || id || '.pdf',
       'application/pdf',
       142000,
       (CASE
            WHEN estado_revision = 'APROBADO' THEN 'verified'
            ELSE 'pending'
           END)::doc_status,
       CURRENT_TIMESTAMP,
       CASE WHEN estado_revision = 'APROBADO' THEN CURRENT_TIMESTAMP ELSE NULL END
FROM entrenadores;

COMMIT;
