server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never

spring:
  datasource:
    # Railway suele proveer estas variables por defecto al vincular servicios
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 # En Railway Free/Hobby, 20 puede ser mucho
      connection-timeout: 20000 # Aumentamos a 20s para el arranque inicial en la nube
      idle-timeout: 30000
      max-lifetime: 2000000

  jpa:
    hibernate:
      ddl-auto: validate # Correcto: la base de datos debe ser inmutable en PROD
    show-sql: false

  flyway:
    enabled: true
    # Simplificación: usar las mismas credenciales que la app para evitar bloqueos
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

logging:
  level:
    root: INFO
    org.hibernate.SQL: ERROR
    # Solo errores en seguridad para no exponer datos sensibles [cite: 25]
    org.springframework.security: WARN

application:
  security:
    pepper: ${SECURITY_PEPPER_PROD}
    jwt:
      secret-key: ${JWT_SECRET_KEY}