spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/grit_db}
    username: ${DB_USERNAME:app_user}
    password: ${DB_PASSWORD:password_de_tu_env}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Grit-HikariPool
      connection-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 10
      max-lifetime: 900000
      idle-timeout: 300000
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: validate # Flyway manda, Hibernate solo valida que todo coincida
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    root: INFO
    grit.sistema.backend: DEBUG
    # Hibernate / JPA: El "rayo X" de tu base de datos
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    # Limpieza de ruido: No queremos ver estadísticas internas a menos que busquemos fugas
    org.hibernate.stat: ERROR
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: ERROR
    # Seguridad: Vital para entender por qué un JWT es rechazado
    org.springframework.security: INFO
    org.springframework.security.web.FilterChainProxy: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springdoc: ERROR

application:
    security:
      pepper: ${SECURITY_PEPPER_PROD:pepper_dev_local_secret_2026}
      jwt:
        # Clave de desarrollo (puede ser conocida por el equipo)
        secret-key: ${JWT_SECRET_KEY:clave_de_desarrollo_muy_larga_y_segura_1234567890}
    storage:
      # Configuración personalizada para nuestro Service
      endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
      access-key: ${STORAGE_ACCESS_KEY:minioadmin}
      secret-key: ${STORAGE_SECRET_KEY:minioadmin}
      bucket-name: grit-certificaciones-entrenadores

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers" # Exponemos solo lo necesario para monitorear
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true # Docker/Kubernetes para saber si la app está lista