spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20  # Más capacidad para muchos usuarios
      connection-timeout: 5000 # Solo 5 segundos (en prod la red debe ser rápida)

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false # Jamás mostrar SQL en logs de producción (seguridad y rendimiento)

  flyway:
    enabled: true
    # En producción, Flyway puede usar un usuario con más permisos que la App
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}

logging:
  level:
    root: INFO
    com.sistema.gritfitprueba: INFO # No queremos llenar el disco con DEBUG en producción
    org.hibernate.SQL: ERROR # Solo logueamos errores de SQL

application:
  security:
    jwt:
      # En PROD no hay valor por defecto. Si no existe la variable, la app NO arranca (Seguridad).
      secret-key: ${JWT_SECRET_KEY}