spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: grit-backend
  jpa:
    open-in-view: false # Buena práctica: evitar consultas extra en la vista

  # Configuración para que los DTO (Records) se serialicen bien
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}
  error:
    include-message: always # Útil para que el frontend sepa qué falló

application:
  security:
    jwt:
      expiration: 900000
      refresh-token:
        expiration: 604800000